### ISSUE TITLE
一直回复正在编，openai的api次数一直没使用

### ISSUE THREAD

**Issue by HsuHeinrich** [wuomzfx/wx-chatgpt#3]
我按照您的教程完整部署了一遍，只修改了api的key，改了下AI_THINKING_MESSAGE和LIMIT_COUNT_RESPONSE提示的文字描述。其余都没做变更。部署和发布也是正常完成的。但是在公众号上测试的时候一直回复AI_THINKING_MESSAGE的提示消息，看了下openai的api，次数也是一直未使用。还请大大有时间解惑下～

**Comment by wuomzfx** [comment]
跟私有化没关系，云托管上日志有截图吗，瞅瞅。

**Comment by HsuHeinrich** [comment]
日志如下：
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/35984768/220896484-b1c5728f-a34c-45d0-88c8-a7a82d317e5c.png">

**Comment by HsuHeinrich** [comment]
这个是操作记录：
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/35984768/220896704-e3250d49-9867-43d4-8328-48de83d259d9.png">

**Comment by wuomzfx** [comment]
某个问题，第一次发送时的日志瞅瞅

**Comment by wuomzfx** [comment]
找一下错误码，如果是 401 错误的话，就是 apikey 失效了

**Comment by HsuHeinrich** [comment]
解决了，我用python调了下api，发现可以使用。所以怀疑是不是在部署的时候操作不对。于是今天就全部删除了重新来一遍，然后我看了部署过程，发现会copy  package.json这个文件
<img width="787" alt="image" src="https://user-images.githubusercontent.com/35984768/221088177-3bcdaec8-a3d4-4327-9f61-dfd479e412bc.png">
于是我打开这个文件，发现存在name和repository还是您的，是不是和我自身仓库不一致的原因。于是我将这两处改成自己的，重新部署发版后就成功了
<img width="540" alt="image" src="https://user-images.githubusercontent.com/35984768/221087753-33a6319e-bcdb-41a2-b265-bb7697d34469.png">

**Comment by Yxiaoping** [comment]
我也是一样的问题，改了 package.json 中的数据后还是一样的问题，一直回复 AI_THINKING_MESSAGE 的提示消息，还能怎么改啊

**Comment by wuomzfx** [comment]
跟 package.json 的仓库地址与仓库名 没关系的，重新部署成功可能是其他方面的原因

**Comment by Yxiaoping** [comment]
Thank you!

**Comment by wuomzfx** [comment]
@Yxiaoping 建议还是发个错误日志看看，第一次请求的错误日志

**Comment by Yxiaoping** [comment]
![image](https://user-images.githubusercontent.com/79390057/221121279-d0c0504f-7c16-422e-84d1-e1faa6bd80e4.png)
一直都是 200，跟上面那个朋友的一样

**Comment by wuomzfx** [comment]
加我微信，晚点我帮你排查把，75851654

**Comment by Yxiaoping** [comment]
好的，谢谢

**Comment by YuukiJyoudai** [comment]
我这出现了相同的问题，看操作日志是报 401/500，是不是微信服务器限制了？

**Comment by Yxiaoping** [comment]
![image](https://user-images.githubusercontent.com/79390057/221481213-c380b82e-f738-4e49-8895-c35eb25f15bb.png)
今天试了一下对 Message 加入 status 的筛选，可以得到 response 这个值，就不是一直回复 MESSAGE_STATUS_THINKING 了

**Comment by niuqiang1** [comment]
有解决吗 我也一直是这个问题

**Comment by wuomzfx** [comment]
国内已经墙了，现在这条路子走不通了

**Comment by niuqiang1** [comment]
> 国内已经墙了，现在这条路子走不通了

okk,还是多谢啦

**Comment by Yxiaoping** [comment]
Thank you!
