### ISSUE TITLE
API被墙

### ISSUE THREAD

**Issue by stvlynn** [wuomzfx/wx-chatgpt#7]
API目前被墙了，请问我需要修改哪些部分来调用我自建的API？非常感谢

**Comment by wuomzfx** [comment]
没辙，我也一样

**Comment by wenlizi** [comment]
目前api不通了是不？

**Comment by stvlynn** [comment]
> 目前api不通了是不？

可以用[cloudflare workers自建api](https://github.com/noobnooc/noobnooc/discussions/9)...但是不知道怎么把自建的api应用到这个上面

**Comment by wuomzfx** [comment]
微信的云托管应该不支持走代理的，所以目前这条路子确实不通了

**Comment by VarPower1989** [comment]
凉了？没有办法搞了？是openAI的接口被墙了？国外服务器能解决吗？

**Comment by wuomzfx** [comment]
国外服务器可以，但这个项目是基于微信云托管的，是不行的。

**Comment by VarPower1989** [comment]
国外服务器做个中转呢？那其实就多此一举了吧

**Comment by wuomzfx** [comment]
你可以不走微信云托管，直接用国外服务器，但我不知道微信能不能直接使用国外服务器。亦或者你用微信云托管或国内服务器，再转发调用另外一台国外服务器，这样也行。但总归是不太合规，还是基于微信在玩，容易被ban。

**Comment by VarPower1989** [comment]
公众号和国外服务器这个搭配应该合规吧？

**Comment by wuomzfx** [comment]
但是你国外服务器调用的是国内不允许的服务，这个就不知道行不行了，我感觉小范围没事，大范围容易被搞，小心为上。

**Comment by VarPower1989** [comment]
嗯嗯。总之感谢🙏。openAI还是主动限制国内，国内已经很火了，反而是openAI墙柱国内接口。
